from naturalnets.environments.anki.pages.profile_page_popups.add_profile_popup_page import AddProfilePopupPage
from naturalnets.environments.anki.pages.profile_page_popups.at_least_one_profile_popup_page import AtLeastOneProfilePopupPage
from naturalnets.environments.anki.pages.profile_page_popups.delete_profile_popup_page import DeleteProfilePopupPage
from naturalnets.environments.anki.pages.profile_page_popups.downgrade_popup_page import DowngradePopupPage
from naturalnets.environments.anki.pages.profile_page_popups.five_profiles_popup_page import FiveProfilesPopupPage
from naturalnets.environments.anki.pages.profile_page_popups.open_backup_popup_page import OpenBackupPopup
from naturalnets.environments.anki.pages.profile_page_popups.rename_profile_popup_page import RenameProfilePage
